# Generated by Django 5.1.6 on 2025-03-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodproject', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
